server:
  port: 9411

spring:
  application:
    name: zipkin-server
  zipkin:
    base-url: http://localhost:9411/
    discoveryclientenabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false