server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080 # \u914D\u7F6Esentinel dashboard\u5730\u5740
        port: 8719 # \u9ED8\u8BA48719\u7AEF\u53E3,\u5047\u5982\u88AB\u5360\u7528\u4F1A\u81EA\u52A8+1

service-url:
  nacos-user-service: http://nacos-payment-provider # \u6D88\u8D39\u8005\u5C06\u8981\u53BB\u8BBF\u95EE\u7684\u5FAE\u670D\u52A1\u540D\u79F0(\u6CE8\u518C\u6210\u529F\u8FDBnaocs\u7684\u5FAE\u670D\u52A1\u63D0\u4F9B\u8005)
feign:
  sentinel:
    enabled: true # \u6FC0\u6D3Bsentinel\u5BF9feign\u7684\u652F\u6301
