server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:defaultZone: http://localhost:8761/eureka/,http://127.0.0.1:8759/eureka/

spring:
  application:
    name: service-hi
