server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange  # \u8868\u793A\u8981\u4F7F\u7528\u7684Exchange\u540D\u79F0\u5B9A\u4E49
          content-type: application/json #\u8BBE\u7F6E\u6D88\u606F\u7C7B\u578B,\u672C\u6B21\u4E3Ajson,\u6587\u672C\u8BBE\u7F6E\u4E3A"text/plain"
          default-binder: defaultRabbit  # \u8BBE\u7F6E\u8981\u7ED1\u5B9A\u7684\u6D88\u606F\u670D\u52A1\u7684\u5177\u4F53\u8BBE\u7F6E
          group: groupA  # \u5206\u7EC4,\u91CD\u590D\u6D88\u8D39\u548C\u6D88\u606F\u6301\u4E45\u5316  \u540C\u4E00\u4E2A\u7EC4\u7684\u4F1A\u7ADE\u4E89,\u53EA\u6709\u4E00\u4E2A\u6536\u5230(\u8F6E\u8BE2),\u4E0D\u540C\u7EC4\u90FD\u4F1A\u6536\u5230;\u4E0D\u52A0\u5206\u7EC4,\u6D88\u606F\u4F1A\u4E22\u5931
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: receive-8802.com  # \u5728\u4FE1\u606F\u5217\u8868\u65F6\u663E\u793A\u4E3B\u673A\u540D\u79F0
    prefer-ip-address: true  # \u8BBF\u95EE\u7684\u8DEF\u5F84\u53D8\u4E3Aip\u5730\u5740
    lease-renewal-interval-in-seconds: 2  # \u8BBE\u7F6E\u5FC3\u8DF3\u65F6\u95F4\u95F4\u9694(\u9ED8\u8BA430s)
    lease-expiration-duration-in-seconds: 5 # \u8BBE\u7F6E\u5982\u679C\u73B0\u5728\u8D85\u8FC7\u4E865s\u7684\u95F4\u9694(\u9ED8\u8BA4\u662F90s)